/** @format */

import Head from 'next/head';
import { io } from 'socket.io-client';
import { useEffect } from 'react';

export default function Home() {
	useEffect(() => {
		fetch('/api/socket').finally(() => {
			const socket = io();

			socket.on('connect', () => {
				console.log('connect');
				socket.emit('hello');
			});

			socket.on('hello', (data) => {
				console.log('hello', data);
			});

			socket.on('a user connected', () => {
				console.log('a user connected');
			});

			socket.on('disconnect', () => {
				console.log('disconnect');
			});
		});
	}, []); // Added [] as useEffect filter so it will be executed only once, when component is mounted

	return (
		<>
			<Head>
				<title>Online Multiplayer Game</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Socket.io</h1>
			<main></main>
		</>
	);
}
