/** @format */

// Import necessary dependencies
import Head from 'next/head';
import { useEffect, useState } from 'react';
import io from 'socket.io-client';

let socket;
export default function Home() {
	useEffect(() => {
		socketInitializer();
	}, []);

	const socketInitializer = () => {
		fetch('/api/socket').then(() => {
			socket = io();

			socket.on('connect', () => {
				console.log('connected');
			});
		});
	};

	const [gameID, setGameID] = useState('');
	const [playerName, setPlayerName] = useState('');

	const handleCreateGame = () => {
		const socket = io();
		// Emit an event to the server to create a new game

		socket.emit('create-game', { playerName });

		// Listen for a response from the server
		socket.on('game-created', (data) => {
			console.info('Game created');
			console.info(data);
		});
		// Redirect to the game lobby with the newly created game code

		// router.push(`/game/${data.gameID}`);
	};

	const handleJoinGame = () => {
		const socket = io();

		// Emit an event to the server to join a game with the provided code
		socket.emit('join-game', { gameID });

		// Listen for a response from the server
		socket.on('game-exists', (exists) => {
			if (exists) {
				// Game exists logic here
			} else {
				console.info('Game does not exist.');
			}
			// Disconnect the socket to avoid potential issues
		});
	};

	return (
		<>
			<Head>
				<title>Wizard Multiplayer Game</title>
				<meta name='description' content='Generated by create next app' />

				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Wizard Multiplayer Game</h1>
			<br />
			<br />
			<input
				type='text'
				placeholder='Enter Player Name'
				value={playerName}
				onChange={(e) => setPlayerName(e.target.value)}
			/>
			<br />
			<br />
			<input
				type='text'
				placeholder='Enter Game Code'
				value={gameID}
				onChange={(e) => setGameID(e.target.value)}
			/>
			<br />
			<br />

			<button onClick={handleCreateGame}>Create Game</button>
			<br />
			{/* <button onClick={handleJoinGame}>Join Game</button> */}
		</>
	);
}
